import { IFigure } from "./IFigure";

export const CHESS_ITEMS: IFigure[] = [
    {
        id: 1,
        item: 'Pawn',
        side: 'black',
        x: 6,
        y: 0,
    },
    {
        id: 2,
        item: 'Pawn',
        side: 'black',
        x: 6,
        y: 1,
    },
    {
        id: 3,
        item: 'Pawn',
        side: 'black',
        x: 6,
        y: 2,
    },
    {
        id: 4,
        item: 'Pawn',
        side: 'black',
        x: 6,
        y: 3,
    },
    {
        id: 5,
        item: 'Pawn',
        side: 'black',
        x: 6,
        y: 4,
    },
    {
        id: 6,
        item: 'Pawn',
        side: 'black',
        x: 6,
        y: 5,
    },
    {
        id: 7,
        item: 'Pawn',
        side: 'black',
        x: 6,
        y: 6,
    },
    {
        id: 8,
        item: 'Pawn',
        side: 'black',
        x: 6,
        y: 7,
    },
    {
        id: 9,
        item: 'Rook',
        side: 'black',
        x: 7,
        y: 7,
    },
    {
        id: 10,
        item: 'Knight',
        side: 'black',
        x: 7,
        y: 6,
    },
    {
        id: 11,
        item: 'Rook',
        side: 'black',
        x: 7,
        y: 0,
    },
    {
        id: 12,
        item: 'Knight',
        side: 'black',
        x: 7,
        y: 1,
    },
    {
        id: 13,
        item: 'Bishop',
        side: 'black',
        x: 7,
        y: 2,
    },
    {
        id: 14,
        item: 'Bishop',
        side: 'black',
        x: 7,
        y: 5,
    },
    {
        id: 15,
        item: 'King',
        side: 'black',
        x: 7,
        y: 3,
    },
    {
        id: 16,
        item: 'Queen',
        side: 'black',
        x: 7,
        y: 4,
    },
    {
        id: 17,
        item: 'Pawn',
        side: 'white',
        x: 1,
        y: 0,
    },
    {
        id: 18,
        item: 'Pawn',
        side: 'white',
        x: 1,
        y: 1,
    },
    {
        id: 19,
        item: 'Pawn',
        side: 'white',
        x: 1,
        y: 2,
    },
    {
        id: 20,
        item: 'Pawn',
        side: 'white',
        x: 1,
        y: 3,
    },
    {
        id: 21,
        item: 'Pawn',
        side: 'white',
        x: 1,
        y: 4,
    },
    {
        id: 22,
        item: 'Pawn',
        side: 'white',
        x: 1,
        y: 5,
    },
    {
        id: 23,
        item: 'Pawn',
        side: 'white',
        x: 1,
        y: 6,
    },
    {
        id: 24,
        item: 'Pawn',
        side: 'white',
        x: 1,
        y: 7,
    },
    {
        id: 25,
        item: 'Rook',
        side: 'white',
        x: 0,
        y: 7,
    },
    {
        id: 26,
        item: 'Rook',
        side: 'white',
        x: 0,
        y: 0,
    },
    {
        id: 27,
        item: 'Knight',
        side: 'white',
        x: 0,
        y: 6,
    },
    {
        id: 28,
        item: 'Knight',
        side: 'white',
        x: 0,
        y: 1,
    },
    {
        id: 29,
        item: 'Bishop',
        side: 'white',
        x: 0,
        y: 2,
    },
    {
        id: 30,
        item: 'Bishop',
        side: 'white',
        x: 0,
        y: 5,
    },
    {
        id: 31,
        item: 'King',
        side: 'white',
        x: 0,
        y: 3,
    },
    {
        id: 32,
        item: 'Queen',
        side: 'white',
        x: 0,
        y: 4,
    },
]